Add hardware to common
osuTitanic/common pull request #11
Opened 2024-09-05 07:14 UTC by Digitalfear117

2024-09-08 11:56 UTC, Lekuruu reviewed
This still won't work, because `DBBenchmark` doesn't have the hardware column.

2024-09-08 12:40 UTC, Digitalfear117 commented
Added

2024-09-09 14:03 UTC, Lekuruu requested changes

2024-09-09 14:03 UTC, Lekuruu commented on database/repositories/benchmarks.py
> +    hardware: str,
This should probably be a `dict` now

2024-09-09 21:36 UTC, Digitalfear117 commented on database/repositories/benchmarks.py
> +    hardware: str,
yes, I have updated it to dict

2024-09-10 14:54 UTC, Lekuruu approved these changes

2024-09-10 14:54 UTC, merged