Add relax score calculation util
osuTitanic/common pull request #3
Opened 2023-11-29 00:53 UTC by kanaarima

Code aims to emulate vanilla scoring on relax

2023-11-29 08:00 UTC, Lekuruu commented
Looks good to me. Is this similar to vn score?

2023-11-29 08:22 UTC, Lekuruu requested changes

2023-11-29 08:22 UTC, Lekuruu commented on helpers/score.py
> +    if mods & Mods.Easy:
I would like to use a different syntax here:
```python
if Mods.Easy in mods
```
This requires the `mods` parameter to be a `Mods` enum.
````python
def calculate_mod_multiplier(mods: Mods)
    …

calculate_mod_multiplier(Mods(score.mods))
```

2023-11-30 04:46 UTC, kanaarima commented
> How does it compare to vn score?

This should be as close as possible to VN score without having to manually process replays, at least for full combos, non full combo will have slight to significantly less than vanilla counterpart

2023-11-30 10:35 UTC, merged